const LOGIN_USER = 'LOGIN_USER';
const USERS_LIST = 'USERS_LIST';
export const USERS_LIST_INIT = `${USERS_LIST}_INIT`;
export const USERS_LIST_SUCCESS = `${USERS_LIST}_SUCCESS`;
export const USERS_LIST_ERROR = `${USERS_LIST}_ERROR`;